[package]
name = "mold"
version = "0.1.0"
authors = ["Aron Bergman <aron@aronbergman.se>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
tempfile = "3"

[dev-dependencies]
tempdir = "0.3.7"

[lib]
path = "lib/lib.rs"
